[package]
name = "codecrafters-sqlite"
version = "0.1.0"
authors = [
	"Codecrafters <hello@codecrafters.io>",
	"Bastiaan M. van de Weerd <bastiaan+git@bm-w.eu>",
]
edition = "2021"

[dependencies]
anyhow = "1.0.59"
itertools = "0.12.1"
thiserror = "1.0.32"
